### PR TITLE
Added a resque-ctl binary

### PR DESCRIPTION
**Pull request by taf2**
I think this might make it easier for people.  It makes deploying workers more like deploying a unicorn app.

I didn't use Process.daemon - since it's not in 1.8.x... Also, having a little bit more control over how the process demonizes allows for finer grained error reporting...

### CODE REVIEW

**Comment by assaf** [comment]
This is purely made of awesome. Just pushed out version 2.0, should be available from Ruby gems shortly.

**Comment by taf2** [comment]
thanks!

**Comment by taf2** [comment]
I just merged your branch into mine again - and have added a few updates to make the command work nicer in a development environment.  Just running "bundle exec resque-ctl" would be enough in a development environment to load 1 worker.

**Comment by taf2** [comment]
Going to open a new pull request, I think that's the right thing to do...

**Pull request closed without merging**
